services:
  next-app:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: 62070096/frontend
    ports:
      - 3000:3000
  express-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: 62070096/backend
    ports:
      - 3030:3030